### ISSUE TITLE
ImproverBot не видит некоторых металлов

### ISSUE THREAD

**Issue by gureev** [IldarW/WurmBot#13]
Как минимум не видит золото

**Comment by TEN4d** [comment]
Не только improve, а и im и возможно другие не видят раскаленные металлы. Частично реагируют на общее "lump", но разделить по металлу не могут.

**Comment by TEN4d** [comment]
Обычный металл называется "iron lumps". после нагрева уже "lump, iron", Указать имя с запятой в боте не получается.
