### ISSUE TITLE
ImproveBot делает большие паузы

### ISSUE THREAD

**Issue by TEN4d** [IldarW/WurmBot#28]
При работе с blacksmiting делает паузу секунд 5-10, потом выдает сообщение "Improve action didn't finish!" и продолжает работать дальше. Через некоторое время все повторяется.

**Comment by gureev** [comment]
Импрувер в целом достаточно много флудит как в лог событий, так и в консоль, причем не только с блэксмитом. Надо разобраться.

**Comment by IldarW** [comment]
Скорее всего проблема решена последним коммитом https://github.com/IldarW/WurmBot/commit/832d7057b2d8841ab3dd2b3c691ad4dd41a7aa29
