### ISSUE TITLE
Добавить для бота-лесоруба возможность выбора инструмента

### ISSUE THREAD

**Issue by IldarW** [IldarW/WurmBot#41]
Кроме стандартного хатчета, рубить также можно боевыми топорами

**Comment by arghaan** [comment]
Это про fr или про ch?

**Comment by IldarW** [comment]
Это просто предложение одного из игроков. fr по идее должен срубать только shriveled деревья, наверное без разницы каким топором

**Comment by IldarW** [comment]
Есть еще бот tc
