### ISSUE TITLE
Сменить дефолтовое состояние параметра "r" крафтинг бота в true

### ISSUE THREAD

**Issue by arghaan** [IldarW/WurmBot#46]
Забываю включать. Потерял уже 2 наковальни по невнимательности.

**Comment by thething0** [comment]
Проблема на данный момент в том, что нельзя определить чинится предмет или нет. И если предмет не чинится, и при этом ломается при крафте, то крафт останавливается. Нужно делать список чинимых вещей, наподобие как в фораджере есть список дропа.

**Comment by TEN4d** [comment]
Если используется предмет на земле, например большая наковальня, то не чинится вообще. То самое и с floor loom.

**Comment by IldarW** [comment]
> Проблема на данный момент в том, что нельзя определить чинится предмет или нет. И если предмет не чинится, и при этом ломается при крафте, то крафт останавливается. Нужно делать список чинимых вещей, наподобие как в фораджере есть список дропа.

Там сейчас просто проверяется дамаг в левом слоте и при необходимости отправляется команда Repair с айдишником предмета из левого слота. Странно что наземные предметы таким образом не чинятся, надо проверить.

**Comment by TheThingG** [comment]
Проблема еще в том, что бот без разбору отправляет команду на починку, и соответственно если предмет неремонтопригоден то все просто зависает. Придется делать проверку на isRepairable, чего в клиенте в принципе нет.
