### ISSUE TITLE
Добавить в Assistant bot больше заклинаний для прокачки ченелинга.

### ISSUE THREAD

**Issue by thething0** [IldarW/WurmBot#56]
Например каст Oppulence у Вайноры, Bless у остальных или прокачку через Vessel на камнях ниже 10q

**Comment by fenume** [comment]
В WU нет смысла в разных кастах, качь идет с одной скоростью. Потому уже реализованных Bless, Dispel, Morning Fog, Light token достаточно.Vessel же полезен только виноре и либиле на высоком ченнелинге, но камней не напасешься для длительного нонстоп кача.

**Comment by thething0** [comment]
Вроде бы сложность все еще влияла. Если нет то как минимум зарядка весселем была бы не лишней. Руками с его сложностью замучаешься

**Comment by fenume** [comment]
Сложность влияет в WO. в WU что блесс, что вессел дают одинаково:
Вессел [16:53:47] Channeling increased by 0,0012 to 61,6226
Блесс [16:54:55] Channeling increased by 0,0012 to 61,6238

Заряжать гемы 10-20ку автоматом конечно неплохо, но и вручную не сложно если забиндить вессел на хоткей.
