### ISSUE TITLE
Wurm Unlimited 1.9.x update - WurmBot crashes client.

### ISSUE THREAD

**Issue by marcus001** [IldarW/WurmBot#61]
WurmBot used to work before the update but Wurm was updated yesterday. The client crashes and will not load with the mod enabled.

**Comment by cprn** [comment]
Can't confirm. Which version did you try? Is there any output if you run Wurm from the command line? What OS are you on?

**Comment by IldarW** [comment]
fixed 586650e22ef6f62235ad5c8d90e9643dbde62711
