### ISSUE TITLE
Still can't load 1.6 to 1.7 but 1.5 loads fine

### ISSUE THREAD

**Issue by cprn** [IldarW/WurmBot#62]
It's related to #60. The last working version was 1.5, newer versions (including 1.7) don't load properly and complain about the missing file. The path resolution used to return `e:/home/shared...` (before e449c62) and now it's missing the leading slash `/`:
```java
java.io.FileNotFoundException: home/shared/Steam/steamapps/common/Wurm Unlimited/WurmLauncher/mods/WurmBot/WurmBot.jar (No such file or directory)
```
The correct absolute path in this case is:
```java
/home/shared/Steam/steamapps/common/Wurm Unlimited/WurmLauncher/mods/WurmBot/WurmBot.jar
```
I understand if you decide to stop supporting Unix users. In such case maybe you'd consider adding `pom.xml` to the repository? Thanks in advance.

**Comment by IldarW** [comment]
Hello
Added pom.xml in dev branch - https://github.com/IldarW/WurmHelper/tree/dev
Also fixed the problem with bot loading, check it out

**Comment by IldarW** [comment]
To install the mod with "mvn clean install" command, configure the "client.location" property in main pom.xml file

**Comment by cprn** [comment]
Unfortunately it doesn't compile on Linux. :( I fixed paths in `pom.xml` and `main/pom.xml` and got stuck on:

```java
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact lwjgl-natives-windows:lwjgl-natives-windows:jar:1.9 at specified path /home/shared/Steam/steamapps/common/Wurm Unlimited/WurmLauncher/lib/lwjgl-natives-windows-2.9.1.jar
```

There's no such library on Linux, there's `lwjgl-natives-linux-2.9.1.jar` but replacing that library and trying to `mvn clean install` again I get a `NullPointerException`:

```java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Main: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Main: Fatal error compiling
```

**Comment by IldarW** [comment]
It turns out this library is not needed in order for the project to compile. Removed it in a recent commit.
You could try again. If you get any more problems, provide full stack trace of the errors(-X flag in Maven)

**Comment by cprn** [comment]
After removing unnecessary dependencies the compilation still stops on NPE (so it wasn't due to `lwjgl-natives-linux-2.9.1.jar` after all). I tried to find the source of the issue myself but its beyond me. Maybe I need to configure something in a compilation plugin? All I did was default Maven install, it used to work out of the box for all other Java projects I ever compiled. The only changes I did in your code base so far were whatever `mvn clean install` complained about. I had to set the `client.location` and `systemPath` values for all JAR files (replacing `\` with `/`) in pom files. Full `-X` log [on Gist](https://gist.github.com/cprn/1742a38578d58c044de60077a5a0c4c5).

**Comment by IldarW** [comment]
Configure maven to use JDK 8 by setting JAVA_HOME environment variable. 
Before execution of "mvn clean install" check JDK version by "mvn --version"
Also modified pom xmls, so you don't need to replace slash characters

**Comment by cprn** [comment]
Hah, it now compiles, installs and loads without issues, thank you! And yeah, a rookie mistake using wrong JDK, won't happen again, sorry for wasting your time.

**Comment by IldarW** [comment]
It is ok, I actually liked this problem solving, and this experience will definitely be useful in the future.
