### ISSUE TITLE
Вынести рубку деревьев в отдельный бот, добавить возможность настройки возраста деревьев под сруб.

### ISSUE THREAD

**Issue by IldarW** [IldarW/WurmBot#7]

**Comment by fenume** [comment]
Так же нужна возможность отключать сбор сажанцев полностью.

**Comment by IldarW** [comment]
Сделано - https://github.com/IldarW/WurmBot/commit/f0ebef3a49029507c20156209bd33fde319d3acd
Но пока не в релизе
